# Publishes the URI endpoints for the environment to a comment of the GitHub pull request.
---
kind: Job
apiVersion: batch/v1
metadata:
  name: "{{ .Release.Name }}-publish-endpoints-github"
  labels:
    app.kubernetes.io/component: post-install-publish-endpoints
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- if .Values.argoCDSupport }}
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    {{- end }}
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-publish-endpoints-github"
      labels:
        app.kubernetes.io/component: post-install-publish-endpoints
    spec:
      {{- if .Values.serviceAccount.name }}
      serviceAccountName: "{{ .Values.serviceAccount.name }}"
      {{- end }}
      restartPolicy: Never
      containers:
        - name: publish-endpoints
          image: "{{ .Values.supportComponents.kubectl.image.name }}:{{ .Values.supportComponents.kubectl.image.tag }}"
          command:
            - "/bin/bash"
            - "-c"
          args:
            - |
              echo "Validating that we can curl GitHub..."
              curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X GET "https://api.github.com/orgs/{{ .Values.github.owner }}"
              
              comment_body=$(cat <<EOF
              Ephemeral Environment Details:
              Web: [{{ template "bitwarden.endpoint.web" . }}]({{ template "bitwarden.endpoint.web" . }})
              Api: [{{ template "bitwarden.endpoint.api" . }}]({{ template "bitwarden.endpoint.api" . }})
              Identity: [{{ template "bitwarden.endpoint.identity" . }}]({{ template "bitwarden.endpoint.identity" . }})

              # Argo CD Environment
              [![Block Label]({{ template "bitwarden.endpoint.argocd-badge" . }})]({{ template "bitwarden.endpoint.argocd" . }})
              EOF
              )

              # Escape newlines and special characters
              comment_body=$(echo "$comment_body" | jq -sR .)

              # Post comment
              echo "GH PR ID: ${GITHUB_PR_ID}"
              echo "GH PROJECT: ${GITHUB_PROJECT}"
              echo "GH OWNER: ${GITHUB_OWNER}"
              COMMENT_ID=$(curl -s -H "Authorization: Bearer ${GITHUB_TOKEN}" -H "Accept: application/json" \
              -d "{\"body\": $comment_body}" \
              "https://api.github.com/repos/${GITHUB_OWNER}/ephemeral-environment-charts/issues/1/comments" | jq)

              echo "$COMMENT_ID" | jq -R -r '.'

          envFrom:
            - secretRef:
                name: {{ template "bitwarden.sharedCloudResourcesSecret" . }}
            - configMapRef:
                name: {{ .Release.Name }}-config-map
